config/routes.rb
Rails.application.routes.draw do
  # verb 'path', to: 'controller#action'

  # see all restaurants
  get 'restaurants', to: 'restaurants#index'

  # create a restaurant
  get 'restaurants/new', to: 'restaurants#new'
  post 'restaurants', to: 'restaurants#create'

  # see one restaurant
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # update a restaurant
  get 'restaurants/:id/edit', to: 'restaurants#edit', as: :edit_restaurant
  patch 'restaurants/:id', to: 'restaurants#update'

  # delete a restaurant
  delete 'restaurants/:id', to: 'restaurants#destroy'

  # resources :restaurants
  # resources :restaurants, only: [:index]
  # resources :restaurants, except: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy

    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Update the restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<p><%= link_to 'back to restaurants', restaurants_path %></p>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

<p><%= link_to "add restaurant", restaurants_new_path %></p>

app/views/restaurants/new.html.erb
<h1>Create restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<p><%= link_to 'back to restaurants', restaurants_path %></p>

app/views/restaurants/show.html.erb
<h1>See restaurant info</h1>

<p><strong>Name:</strong> <%= @restaurant.name %> </p>
<p><strong>Address:</strong> <%= @restaurant.address %> </p>
<p><strong>Rating:</strong> <%= @restaurant.rating %> </p>


<%= link_to 'back to restaurants', restaurants_path %> |
<%= link_to 'update restaurant', edit_restaurant_path(@restaurant) %> |
<%= link_to 'delete', restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: 'r u sure?' } %>